import 'dotenv/config'

export const env = {
    MONGODB_URI: process.env.MONGODB_URI,
    DATABASE_NAME: process.env.DATABASE_NAME,
    APP_HOST: process.env.APP_HOST,
    APP_PORT: process.env.APP_PORT,
    BUILD_MODE: process.env.BUILD_MODE,
    AUTHOR: process.env.AUTHOR,
    WEBSITE_DOMAIN_DEVELOPMENT: process.env.WEBSITE_DOMAIN_DEVELOPMENT,
    WEBSITE_DOMAIN_PRODUCTION: process.env.WEBSITE_DOMAIN_PRODUCTION,

    // Brevo
    BREVO_API_KEY: process.env.BREVO_API_KEY,
    ADMIN_EMAIL_ADDRESS: process.env.ADMIN_EMAIL_ADDRESS,
    ADMIN_EMAIL_NAME: process.env.ADMIN_EMAIL_NAME,

    ACCESS_TOKEN_SECRET_SIGNATURE: process.env.ACCESS_TOKEN_SECRET_SIGNATURE,
    ACCESS_TOKEN_LIFE: process.env.ACCESS_TOKEN_LIFE,

    REFRESH_TOKEN_SECRET_SIGNATURE: process.env.REFRESH_TOKEN_SECRET_SIGNATURE,
    REFRESH_TOKEN_LIFE: process.env.REFRESH_TOKEN_LIFE,

    API_CLOUD_NAME: process.env.API_CLOUD_NAME,
    API_CLOUD_KEY: process.env.API_CLOUD_KEY,
    API_CLOUD_SECRET: process.env.API_CLOUD_SECRET

}